import React, { useEffect, useMemo, useRef, useState } from "react";
import { io } from "socket.io-client";

const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:5000";
function apiFetch(path, auth, options = {}) {
  return fetch(API_BASE + path, {...options, headers: {"Content-Type":"application/json", ...(auth?.token ? {Authorization:"Bearer "+auth.token}:{}), ...(options.headers||{})}})
    .then(async r => { const d=await r.json().catch(()=>({})); if(!r.ok) throw new Error(d.message||"API request failed"); return d; });
}
export default function App() {
  const [auth,setAuth]=useState(()=>{try{return JSON.parse(localStorage.getItem("shivasha_auth"))||null}catch{return null}});
  if(!auth) return <Login onLogin={setAuth}/>;
  return <SocialApp auth={auth} setAuth={setAuth} onLogout={()=>{localStorage.removeItem("shivasha_auth");setAuth(null)}}/>;
}
function Login({onLogin}) {
  const [mode,setMode]=useState("login"),[form,setForm]=useState({name:"",email:"",password:""}),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);
  const submit=async e=>{e.preventDefault();setMessage("");setLoading(true);try{const d=await apiFetch("/api/auth/"+mode,null,{method:"POST",body:JSON.stringify(form)});if(mode==="register"){setMode("login");setMessage("Account created. Now login.")}else{localStorage.setItem("shivasha_auth",JSON.stringify(d));onLogin(d)}}catch(e){setMessage(e.message)}finally{setLoading(false)}};
  return <div className="login-page"><div className="login-card"><div className="shivasha-logo">S</div><div className="login-brand"><b>SHIVASHA</b><small>Social • Connect • Share</small></div><p className="eyebrow">SOCIAL COMMUNITY PLATFORM</p><h1>{mode==="login"?"Welcome to SHIVASHA":"Join SHIVASHA"}</h1><p className="muted">{mode==="login"?"Connect with people and share what matters.":"Create your profile and start connecting."}</p><form onSubmit={submit}>{mode==="register"&&<label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></label>}<label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="name@example.com"/></label><label>Password<input required minLength="6" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Minimum 6 characters"/></label><button className="primary login-button" disabled={loading}>{loading?"Please wait...":mode==="login"?"Login":"Create account"}</button></form>{message&&<div className="login-message">{message}</div>}<button className="switch-auth" onClick={()=>{setMode(mode==="login"?"register":"login");setMessage("")}}>{mode==="login"?"Create a new account":"Already have an account? Login"}</button></div></div>;
}
function Avatar({user,large=false}){const letter=(user?.name||"S").trim().charAt(0).toUpperCase();return user?.avatarUrl?<img className={large?"avatar large":"avatar"} src={user.avatarUrl} alt=""/>:<div className={large?"avatar large":"avatar"}>{letter}</div>}
function SocialApp({auth,setAuth,onLogout}) {
  const [realtime,setRealtime]=useState("connecting");
  const [onlineUsers,setOnlineUsers]=useState([]);\n  useEffect(()=>{const socket=io(API_BASE,{auth:{token:auth?.token}});setSocket(socket);socket.on("connect",()=>setRealtime("online"));socket.on("disconnect",()=>setRealtime("offline"));socket.on("connect_error",()=>setRealtime("offline"));socket.on("message:new",m=>{setMessages(prev=>prev.some(x=>x._id===m._id)?prev:[...prev,m]);setConversations(prev=>prev.map(c=>c._id===m.conversation?{...c,lastMessage:m,updatedAt:m.createdAt}:c).sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)))});socket.on("notification:new",async()=>{try{const d=await apiFetch("/api/notifications",auth);setNotifications(d.notifications);setUnread(d.unread)}catch{}});socket.on("presence:list",d=>setOnlineUsers(d.userIds||[]));socket.on("presence:online",d=>setOnlineUsers(prev=>prev.includes(d.userId)?prev:[...prev,d.userId]));socket.on("presence:offline",d=>setOnlineUsers(prev=>prev.filter(id=>id!==d.userId)));socket.on("typing:start",d=>{if(activeConversationRef.current?._id===d.conversationId)setTypingUser(true)});socket.on("typing:stop",d=>{if(activeConversationRef.current?._id===d.conversationId)setTypingUser(false)});return()=>{setSocket(null);socket.disconnect()}},[auth?.token]);
  const [active,setActive]=useState("home"),[posts,setPosts]=useState([]),[me,setMe]=useState(auth.user),[discover,setDiscover]=useState([]),[query,setQuery]=useState(""),[searchResults,setSearchResults]=useState([]),[hashtag,setHashtag]=useState(""),[savedPosts,setSavedPosts]=useState([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[notifications,setNotifications]=useState([]),[unread,setUnread]=useState(0),[showNotifications,setShowNotifications]=useState(false);
  const load=async()=>{setLoading(true);setMessage("");try{const [postData,meData,users,notificationResponse]=await Promise.all([apiFetch("/api/posts",auth),apiFetch("/api/users/me",auth),apiFetch("/api/users/discover",auth),apiFetch("/api/notifications",auth)]);setPosts(postData);setMe(meData.user);setDiscover(users);setNotifications(notificationResponse.notifications);setUnread(notificationResponse.unread);const next={...auth,user:meData.user};setAuth(next);localStorage.setItem("shivasha_auth",JSON.stringify(next))}catch(e){setMessage(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  useEffect(()=>{const q=query.trim();if(q.length<2){setSearchResults([]);return}const t=setTimeout(async()=>{try{setSearchResults(await apiFetch("/api/users/search?q="+encodeURIComponent(q),auth))}catch{setSearchResults([])}},300);return()=>clearTimeout(t)},[query]);
  const visibleUsers=useMemo(()=>discover.filter(u=>(u.name+" "+(u.bio||"")).toLowerCase().includes(query.toLowerCase())),[discover,query]);
  const updatePost=p=>setPosts(prev=>prev.map(x=>x._id===p._id?p:x));
  const createPost=async(text,images)=>{try{const p=await apiFetch("/api/posts",auth,{method:"POST",body:JSON.stringify({text,images})});setPosts(prev=>[p,...prev]);setActive("home")}catch(e){setMessage(e.message)}};
  const like=async id=>{try{updatePost(await apiFetch("/api/posts/"+id+"/like",auth,{method:"POST"}))}catch(e){setMessage(e.message)}};
  const comment=async(id,text)=>{try{updatePost(await apiFetch("/api/posts/"+id+"/comments",auth,{method:"POST",body:JSON.stringify({text})})}catch(e){setMessage(e.message)}};
  const repost=async id=>{try{const p=await apiFetch("/api/posts/"+id+"/repost",auth,{method:"POST",body:JSON.stringify({})});setPosts(prev=>[p,...prev]);setMessage("Post reposted")}catch(e){setMessage(e.message)}};
  const reply=async(postId,commentId,text)=>{try{updatePost(await apiFetch("/api/posts/"+postId+"/comments/"+commentId+"/replies",auth,{method:"POST",body:JSON.stringify({text})}))}catch(e){setMessage(e.message)}};
  const openPost=async id=>{try{const p=await apiFetch("/api/posts/"+id,auth);setViewPost(p);setActive("post-detail")}catch(e){setMessage(e.message)}};
  const savePost=async id=>{try{const r=await apiFetch("/api/posts/"+id+"/save",auth,{method:"POST"});setMessage(r.saved?"Post saved":"Post removed from saved");if(active==="saved")setSavedPosts(await apiFetch("/api/posts/saved",auth))}catch(e){setMessage(e.message)}};
  const openSaved=async()=>{try{setSavedPosts(await apiFetch("/api/posts/saved",auth));setActive("saved")}catch(e){setMessage(e.message)}};
  const openHashtag=async tag=>{try{setHashtag(tag);setPosts(await apiFetch("/api/posts?hashtag="+encodeURIComponent(tag),auth));setActive("hashtag")}catch(e){setMessage(e.message)}};
  const deletePost=async id=>{if(!window.confirm("Delete this post?"))return;try{await apiFetch("/api/posts/"+id,auth,{method:"DELETE"});setPosts(prev=>prev.filter(p=>p._id!==id));setSavedPosts(prev=>prev.filter(p=>p._id!==id))}catch(e){setMessage(e.message)}};
  const follow=async id=>{try{await apiFetch("/api/users/"+id+"/follow",auth,{method:"POST"});setDiscover(await apiFetch("/api/users/discover",auth));setMe((await apiFetch("/api/users/me",auth)).user)}catch(e){setMessage(e.message)}};
  const markNotifications=async()=>{setShowNotifications(v=>!v);if(unread){try{await apiFetch("/api/notifications/read",auth,{method:"POST"});setUnread(0)}catch(e){setMessage(e.message)}}};
  const [viewUser,setViewUser]=useState(null),[connections,setConnections]=useState(null),[viewPost,setViewPost]=useState(null),[conversations,setConversations]=useState([]),[activeConversation,setActiveConversation]=useState(null),[messages,setMessages]=useState([]);
  const activeConversationRef=useRef(null);
  const openMessages=async()=>{try{setConversations(await apiFetch("/api/messages/conversations",auth));setActive("messages")}catch(e){setMessage(e.message)}};
  const openConversation=async conversation=>{try{activeConversationRef.current=conversation;setActiveConversation(conversation);setTypingUser(false);socket?.emit("conversation:join",{conversationId:conversation._id});setMessages(await apiFetch("/api/messages/conversations/"+conversation._id+"/messages",auth));await apiFetch("/api/messages/conversations/"+conversation._id+"/read",auth,{method:"POST"});setConversations(prev=>prev.map(c=>c._id===conversation._id?{...c,unreadCount:0}:c))}catch(e){setMessage(e.message)}};
  const startConversation=async userId=>{try{const conversation=await apiFetch("/api/messages/conversations",auth,{method:"POST",body:JSON.stringify({userId})});await openMessages();await openConversation(conversation)}catch(e){setMessage(e.message)}};
  const sendMessage=async text=>{if(!activeConversation||!text.trim())return;try{const m=await apiFetch("/api/messages/conversations/"+activeConversation._id+"/messages",auth,{method:"POST",body:JSON.stringify({text:text.trim()})});setMessages(prev=>prev.some(x=>x._id===m._id)?prev:[...prev,m]);setConversations(prev=>prev.map(c=>c._id===activeConversation._id?{...c,lastMessage:m,updatedAt:m.createdAt,unreadCount:0}:c).sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)))}catch(e){setMessage(e.message)}};

  const openUser=async id=>{try{const d=await apiFetch("/api/users/"+id,auth);setViewUser(d);setConnections(null);setActive("user-profile");setQuery("");setSearchResults([])}catch(e){setMessage(e.message)}};
  const openConnections=async type=>{if(!viewUser?.user)return;try{setConnections({type,users:await apiFetch("/api/users/"+viewUser.user._id+"/connections?type="+type,auth)}.users)}catch(e){setMessage(e.message)}};
  const chooseUser=u=>openUser(u._id);
  const followViewed=async()=>{if(!viewUser?.user)return;try{const r=await apiFetch("/api/users/"+viewUser.user._id+"/follow",auth,{method:"POST"});setViewUser(v=>({...v,isFollowing:r.following,user:{...v.user,followers:r.following?[...(v.user.followers||[]),me._id]: (v.user.followers||[]).filter(x=>(x._id||x).toString()!==me._id.toString())}}));}catch(e){setMessage(e.message)}};
  return <div className="social-shell">
    <header className="mobile-header"><b>SHIVASHA</b><button onClick={onLogout}>Logout</button></header>
    <aside className="sidebar"><div className="brand"><div className="brand-mark">S</div><div><b>SHIVASHA</b><small>Social • Connect • Share</small></div></div><nav>{[["home","⌂","Home"],["discover","◎","Discover"],["create","＋","Create Post"],["messages","✉","Messages"],["saved","🔖","Saved Posts"],["profile","◉","Profile"]].map(([key,icon,label])=><button key={key} className={active===key?"nav-item active":"nav-item"} onClick={()=>key==="saved"?openSaved():key==="messages"?openMessages():setActive(key)}><span>{icon}</span>{label}</button>)}</nav><div className="sidebar-user"><Avatar user={me}/><div><b>{me?.name}</b><small>@{(me?.email||"").split("@")[0]}</small></div></div><button className="logout" onClick={onLogout}>Logout</button></aside>
    <main className="main"><header className="topbar"><div><span className="eyebrow">SHIVASHA</span><h1>{active==="home"?"Home":active==="discover"?"Discover":active==="create"?"Create Post":active==="saved"?"Saved Posts":active==="hashtag"?"#"+hashtag:"My Profile"}</h1></div><div className="realtime-status">{realtime==="online"?"● Live":"○ Offline"}</div><div className="top-actions search-wrap"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search people..."/>{searchResults.length>0&&<div className="search-results">{searchResults.map(u=><button key={u._id} onClick={()=>chooseUser(u)}><Avatar user={u}/><span><b>{u.name}</b><small>{u.bio||u.email}</small></span></button>)}</div>}<button className="notification-button" onClick={markNotifications}>🔔{unread>0&&<span className="notification-badge">{unread>99?"99+":unread}</span>}</button><Avatar user={me}/></div></header>
      {message&&<div className="api-error">{message}</div>}{showNotifications&&<Notifications items={notifications}/>}
      {active==="home"&&<section className="content"><div className="feed-head"><div><h2>Your Feed</h2><p>Latest posts from the SHIVASHA community.</p></div><button className="primary" onClick={()=>setActive("create")}>+ Create</button></div>{loading?<div className="empty">Loading feed...</div>:posts.length?posts.map(p=><PostCard key={p._id} post={p} me={me} onLike={like} onComment={comment} onDelete={deletePost} onSave={savePost} onHashtag={openHashtag} onRepost={repost} onReply={reply} onOpen={openPost}/>):<div className="panel empty">No posts yet. Create the first SHIVASHA post.</div>}</section>}
      {active==="create"&&<CreatePost onCreate={createPost}/>}{active==="messages"&&<Messenger conversations={conversations} activeConversation={activeConversation} messages={messages} me={me} onOpen={openConversation} onSend={sendMessage} socket={socket} typingUser={typingUser} onlineUsers={onlineUsers}/>}
      {active==="discover"&&<Discover users={visibleUsers} me={me} onFollow={follow} onUser={openUser}/>}
      {active==="user-profile"&&viewUser&&<PublicProfile data={viewUser} me={me} onFollow={followViewed} onPostHashtag={openHashtag}/>} {active==="post-detail"&&viewPost&&<PostDetail post={viewPost} me={me} onLike={like} onComment={comment} onDelete={deletePost} onSave={savePost} onHashtag={openHashtag} onRepost={repost} onReply={reply}/>}
      {active==="saved"&&<section className="content"><div className="feed-head"><div><h2>Saved Posts</h2><p>Your bookmarked SHIVASHA posts.</p></div></div>{savedPosts.length?savedPosts.map(p=><PostCard key={p._id} post={p} me={me} onLike={like} onComment={comment} onDelete={deletePost} onSave={savePost} onHashtag={openHashtag}/>):<div className="panel empty">No saved posts yet.</div>}</section>}
      {active==="hashtag"&&<section className="content"><div className="feed-head"><div><h2>#{hashtag}</h2><p>Posts using this hashtag.</p></div><button className="secondary" onClick={()=>setActive("home")}>Back to Home</button></div>{posts.length?posts.map(p=><PostCard key={p._id} post={p} me={me} onLike={like} onComment={comment} onDelete={deletePost} onSave={savePost} onHashtag={openHashtag}/>):<div className="panel empty">No posts found for this hashtag.</div>}</section>}
      {active==="profile"&&<Profile me={me} posts={posts.filter(p=>p.author?._id===me?._id:p.author===me?._id)} auth={auth} onSaved={u=>{setMe(u);setAuth({...auth,user:u});localStorage.setItem("shivasha_auth",JSON.stringify({...auth,user:u}))}}/>}
    </main>
  </div>;
}
function Messenger({conversations,activeConversation,messages,me,onOpen,onSend}) {
  const [text,setText]=useState(""),[typing,setTyping]=useState(false);
  const other=activeConversation?.participants?.find(u=>u._id!==me?._id);
  return <section className="content messenger"><div className="messenger-layout"><div className="conversation-list"><div className="panel-head"><h3>Messages</h3></div>{conversations.length?conversations.map(c=>{const u=c.participants?.find(x=>x._id!==me?._id);return <button className={activeConversation?._id===c._id?"conversation active":"conversation"} key={c._id} onClick={()=>onOpen(c)}><Avatar user={u}/><span><b>{u?.name||"SHIVASHA member"} {c.unreadCount>0&&<em className="message-unread">{c.unreadCount}</em>}</b><small>{c.lastMessage?.text||"Start a conversation"}</small></span></button>}):<div className="empty">No conversations yet.</div>}</div><div className="chat-panel">{activeConversation?<><div className="chat-head"><Avatar user={other}/><div><b>{other?.name}</b><small>{onlineUsers.includes(other?._id)?"● Online":"Offline"}{typingUser?" • Typing…":""}</small></div></div><div className="chat-messages">{messages.map(m=><div key={m._id} className={m.sender?._id===me?._id?"message mine":"message"}><span>{m.text}</span><small>{new Date(m.createdAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</small></div>)}</div><form className="chat-form" onSubmit={e=>{e.preventDefault();if(text.trim()){onSend(text);setText("")}}}><input value={text} onChange={handleTyping} placeholder="Write a message..."/><button className="primary">Send</button></form></>:<div className="empty">Select a conversation to start messaging.</div>}</div></div></section>}
\nfunction Notifications({items}){return <div className="notifications-panel"><div className="panel-head"><h3>Notifications</h3></div>{items.length?items.map(n=><div className="notification-item" key={n._id}><Avatar user={n.actor}/><div><b>{n.actor?.name||"Someone"}</b> {n.type==="like"?"liked your post":n.type==="comment"?"commented on your post":n.type==="repost"?"reposted your post":"started following you"}<small>{new Date(n.createdAt).toLocaleString()}</small></div></div>):<div className="empty">No notifications yet.</div>}</div>}
function PostCard({post,me,onLike,onComment,onDelete,onSave,onHashtag,onRepost,onReply,onOpen}) {
  const [text,setText]=useState("");
  const liked=post.likes?.some(id=>(id._id||id).toString()===(me?.id||me?._id)?.toString());
  const images=post.images?.length?post.images:[post.imageUrl].filter(Boolean);
  return <article className="post-card"><div className="post-author"><Avatar user={post.author}/><div><b>{post.author?.name}</b><small>{new Date(post.createdAt).toLocaleString()}</small></div>{(post.author?._id||post.author)===(me?.id||me?._id)&&<button className="delete-post" onClick={()=>onDelete(post._id)}>Delete</button>}</div>{post.repostOf&&<div className="repost-label">↻ Reposted from {post.repostOf?.author?.name||"SHIVASHA member"}</div>}{post.text&&<p className="post-text">{renderHashtags(post.text,onHashtag)}</p>}{images.length>0&&<PostGallery images={images}/>}<div className="post-actions"><button className={liked?"liked":""} onClick={()=>onLike(post._id)}>♥ {post.likes?.length||0}</button><button onClick={()=>onSave(post._id)}>🔖 Save</button><button onClick={()=>onRepost(post._id)}>↻ Repost</button><button onClick={()=>onOpen(post._id)}>💬 {post.comments?.length||0}</button></div><div className="comments">{post.comments?.slice(-3).map(c=><CommentBlock key={c._id} comment={c} postId={post._id} me={me} onReply={onReply}/>)}</div><form className="comment-form" onSubmit={e=>{e.preventDefault();if(text.trim()){onComment(post._id,text.trim());setText("")}}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a comment..."/><button>Post</button></form></article>;
}
function CommentBlock({comment,postId,me,onReply}){const [replyText,setReplyText]=useState(""),[show,setShow]=useState(false);return <div className="comment"><b>{comment.user?.name}</b> {comment.text}<button className="reply-button" onClick={()=>setShow(v=>!v)}>Reply</button>{comment.replies?.map(r=><div className="comment-reply" key={r._id}><b>{r.user?.name}</b> {r.text}</div>)}{show&&<form className="comment-form reply-form" onSubmit={e=>{e.preventDefault();if(replyText.trim()){onReply(postId,comment._id,replyText.trim());setReplyText("")}}}><input value={replyText} onChange={e=>setReplyText(e.target.value)} placeholder="Write a reply..."/><button>Reply</button></form>}</div>}
function PostDetail({post,...props}){return <section className="content narrow"><div className="feed-head"><div><h2>Post</h2><p>Post details and conversation.</p></div><button className="secondary" onClick={()=>window.history.back()}>Back</button></div><PostCard post={post} {...props} onOpen={()=>{}}/></section>}
function renderHashtags(text,onHashtag){return text.split(/(#[a-zA-Z0-9_]+)/g).map((part,i)=>part.startsWith("#")?<button type="button" className="hashtag-link" key={i} onClick={()=>onHashtag(part.slice(1))}>{part}</button>:part)}
function PostGallery({images}){const [index,setIndex]=useState(0);if(!images?.length)return null;return <div className="post-gallery"><img className="post-image" src={images[index]} alt={"Post image "+(index+1)}/>{images.length>1&&<div className="gallery-controls"><button onClick={()=>setIndex((index-1+images.length)%images.length)}>‹</button><span>{index+1} / {images.length}</span><button onClick={()=>setIndex((index+1)%images.length)}>›</button></div>}</div>}
function CreatePost({onCreate}){const [text,setText]=useState(""),[images,setImages]=useState([]),[file,setFile]=useState(null),[uploading,setUploading]=useState(false),[error,setError]=useState(""),[imageUrl,setImageUrl]=useState("");
  const pick=async e=>{const files=[...(e.target.files||[])];if(!files.length)return;if(files.length>6){setError("Maximum 6 images per post");return}const tooBig=files.find(f=>f.size>2*1024*1024);if(tooBig){setError("Each image must be 2 MB or smaller");return}setFile(files);setError("");setUploading(true);try{const data=new FormData();files.forEach(f=>data.append("images",f));const token=JSON.parse(localStorage.getItem("shivasha_auth"))?.token;const r=await fetch(API_BASE+"/api/posts/upload",{method:"POST",headers:{Authorization:"Bearer "+token},body:data});const d=await r.json();if(!r.ok)throw new Error(d.message||"Upload failed");setImages(d.imageUrls)}catch(e){setError(e.message);setFile(null);setImages([])}finally{setUploading(false)}};
  const publish=()=>{const urls=imageUrl.trim()?[...images,imageUrl.trim()]:images;onCreate(text.trim(),urls)};
  return <section className="content narrow"><div className="panel"><div className="panel-head"><h2>Create a Post</h2></div><textarea className="post-composer" value={text} onChange={e=>setText(e.target.value)} placeholder="What do you want to share? Use #hashtags" maxLength="2000"/><label>Upload images (max 6, 2 MB each)<input type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif" onChange={pick}/></label>{file?.length>0&&<div className="upload-preview">{file.map((f,i)=><div key={f.name+i}><img src={images[i]||URL.createObjectURL(f)} alt="Preview"/><span>{f.name}</span></div>)}</div>}{error&&<div className="login-message">{error}</div>}<label>Optional Image URL<input value={imageUrl} onChange={e=>setImageUrl(e.target.value)} placeholder="https://example.com/image.jpg"/></label><button className="primary" disabled={uploading||(!text.trim()&&!images.length&&!imageUrl.trim())} onClick={publish}>{uploading?"Uploading...":"Publish Post"}</button></div></section>}
function PublicProfile({data,me,onFollow,onPostHashtag}){const u=data.user;return <section className="content"><div className="public-profile"><Avatar user={u} large/><div className="public-profile-main"><h2>{u.name}</h2><p>{u.bio||"SHIVASHA member"}</p><div className="profile-stats"><button className="stat-button" onClick={()=>openConnections("followers")}><b>{u.followers?.length||0}<small>Followers</small></b></button><button className="stat-button" onClick={()=>openConnections("following")}><b>{u.following?.length||0}<small>Following</small></b></button><b>{data.posts?.length||0}<small>Posts</small></b></div><button className={data.isFollowing?"secondary":"primary"} onClick={onFollow}>{data.isFollowing?"Following":"Follow"}</button></div></div>{connections&&<div className="panel connections-panel"><div className="panel-head"><h3>{connections.length ? "Connections" : "No connections"}</h3><button className="secondary" onClick={()=>setConnections(null)}>Close</button></div>{connections.map(u=><button className="connection-row" key={u._id} onClick={()=>openUser(u._id)}><Avatar user={u}/><span><b>{u.name}</b><small>{u.bio||"SHIVASHA member"}</small></span></button>)}</div>}<div className="profile-posts">{data.posts?.length?data.posts.map(p=><PostCard key={p._id} post={p} me={me} onLike={()=>{}} onComment={()=>{}} onDelete={()=>{}} onSave={()=>{}} onHashtag={onPostHashtag}/>):<div className="panel empty">No posts yet.</div>}</div></section>}
function Discover({users,me,onFollow,onUser}){return <section className="content"><div className="feed-head"><div><h2>Discover People</h2><p>Find people and grow your SHIVASHA network.</p></div></div><div className="people-grid">{users.map(u=>{const following=u.followers?.some(id=>(id._id||id).toString()===(me?.id||me?._id)?.toString());return <div className="person-card" key={u._id} onClick={()=>onUser(u._id)}><Avatar user={u} large/><h3>{u.name}</h3><p>{u.bio||"SHIVASHA member"}</p><small>{u.followers?.length||0} followers</small><button className={following?"secondary":"primary"} onClick={e=>{e.stopPropagation();onFollow(u._id)}}>{following?"Following":"Follow"}</button></div>})}</div></section>}
function Profile({me,posts,auth,onSaved}){const [name,setName]=useState(me?.name||""),[bio,setBio]=useState(me?.bio||""),[avatarUrl,setAvatarUrl]=useState(me?.avatarUrl||""),[saved,setSaved]=useState("");const save=async()=>{try{const r=await apiFetch("/api/users/me",auth,{method:"PATCH",body:JSON.stringify({name,bio,avatarUrl})});onSaved(r.user);setSaved("Profile saved")}catch(e){setSaved(e.message)}};return <section className="content narrow"><div className="profile-hero"><Avatar user={{...me,avatarUrl,name}} large/><div><h2>{name}</h2><p>{bio||"Welcome to SHIVASHA."}</p><div className="profile-stats"><b>{me?.followers?.length||0}<small>Followers</small></b><b>{me?.following?.length||0}<small>Following</small></b><b>{posts.length}<small>Posts</small></b></div></div></div><div className="panel"><h3>Edit Profile</h3><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Bio<textarea value={bio} onChange={e=>setBio(e.target.value)} maxLength="280"/></label><label>Avatar URL<input value={avatarUrl} onChange={e=>setAvatarUrl(e.target.value)} placeholder="https://example.com/avatar.jpg"/></label><button className="primary" onClick={save}>Save Profile</button>{saved&&<span className="save-message">{saved}</span>}</div></section>}
